return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "2020.06.25",
  orientation = "orthogonal",
  renderorder = "left-down",
  width = 64,
  height = 64,
  tilewidth = 8,
  tileheight = 8,
  nextlayerid = 9,
  nextobjectid = 106,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "grounds",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      tintcolor = { 85, 170, 255 },
      properties = {},
      objects = {
        {
          id = 31,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 168,
          width = 176,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 168,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 0,
          width = 176,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "groundC",
          type = "",
          shape = "rectangle",
          x = 344,
          y = 0,
          width = 168,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 168,
          width = 168,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "groundC",
          type = "",
          shape = "rectangle",
          x = 344,
          y = 168,
          width = 168,
          height = 176,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "groundD",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 344,
          width = 168,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 344,
          width = 176,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "groundD",
          type = "",
          shape = "rectangle",
          x = 344,
          y = 344,
          width = 168,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "playables",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 32,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 240,
          y = 256,
          width = 9,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "walls",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      tintcolor = { 85, 255, 255 },
      properties = {},
      objects = {
        {
          id = 36,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 344,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 344,
          y = 0,
          width = 168,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 504,
          y = 8,
          width = 8,
          height = 336,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 336,
          width = 64,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 336,
          width = 56,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 336,
          width = 176,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 168,
          width = 8,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 272,
          width = 8,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 344,
          y = 336,
          width = 64,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 336,
          width = 56,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 344,
          width = 8,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 504,
          width = 160,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 504,
          width = 176,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 344,
          y = 504,
          width = 160,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 504,
          y = 344,
          width = 8,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 168,
          width = 160,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 168,
          width = 8,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 224,
          width = 8,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 8,
          width = 8,
          height = 328,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "shapes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 32,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 64,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 112,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 32,
          width = 24,
          height = 24,
          rotation = 45,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 72,
          width = 24,
          height = 24,
          rotation = 45,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 312,
          y = 32,
          width = 24,
          height = 24,
          rotation = 45,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 296,
          y = 64,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "ellipse",
          x = 416,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "ellipse",
          x = 424,
          y = 72,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "ellipse",
          x = 480,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "ellipse",
          x = 408,
          y = 232,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "ellipse",
          x = 408,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "ellipse",
          x = 416,
          y = 84,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 216,
          y = 64,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 232,
          y = 112,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 184,
          y = 208,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 136,
          y = 208,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 184,
          y = 112,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 136,
          y = 152,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 408,
          y = 96,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 416,
          y = 56,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 400,
          y = 52,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 416,
          y = 104,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 480,
          y = 96,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 248,
          y = 112,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 192,
          y = 72,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 320,
          y = 68,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 168,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "ellipse",
          x = 240,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "ellipse",
          x = 240,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 104,
          name = "a8",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 248,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "fbxs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 105,
          name = "fbx01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 250,
          width = 2,
          height = 2,
          rotation = 180,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
