return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "2020.06.25",
  orientation = "orthogonal",
  renderorder = "left-down",
  width = 64,
  height = 64,
  tilewidth = 4,
  tileheight = 4,
  nextlayerid = 9,
  nextobjectid = 107,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "grounds",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      tintcolor = { 85, 170, 255 },
      properties = {},
      objects = {
        {
          id = 31,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 84,
          width = 88,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 84,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 0,
          width = 88,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "groundC",
          type = "",
          shape = "rectangle",
          x = 172,
          y = 0,
          width = 84,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 84,
          width = 84,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "groundC",
          type = "",
          shape = "rectangle",
          x = 172,
          y = 84,
          width = 84,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "groundD",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 172,
          width = 84,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 172,
          width = 88,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "groundD",
          type = "",
          shape = "rectangle",
          x = 172,
          y = 172,
          width = 84,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "playables",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 32,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 121,
          y = 129,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "walls",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      tintcolor = { 85, 255, 255 },
      properties = {},
      objects = {
        {
          id = 36,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 172,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 172,
          y = 0,
          width = 84,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 252,
          y = 4,
          width = 4,
          height = 168,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 4,
          y = 168,
          width = 32,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 168,
          width = 28,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 168,
          width = 88,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 84,
          width = 4,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 136,
          width = 4,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 172,
          y = 168,
          width = 32,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 168,
          width = 28,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 172,
          width = 4,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 4,
          y = 252,
          width = 80,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 252,
          width = 88,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 172,
          y = 252,
          width = 80,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 252,
          y = 172,
          width = 4,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 84,
          width = 80,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 84,
          width = 4,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "wallA",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 112,
          width = 4,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "wallB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 4,
          width = 4,
          height = 164,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "shapes",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 20,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 36,
          y = 32,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 60,
          y = 56,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 100,
          y = 16,
          width = 12,
          height = 12,
          rotation = 45,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 36,
          width = 12,
          height = 12,
          rotation = 45,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 156,
          y = 16,
          width = 12,
          height = 12,
          rotation = 45,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 148,
          y = 32,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "ellipse",
          x = 208,
          y = 16,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "ellipse",
          x = 212,
          y = 36,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "ellipse",
          x = 240,
          y = 40,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "ellipse",
          x = 204,
          y = 116,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "ellipse",
          x = 204,
          y = 20,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "ellipse",
          x = 208,
          y = 42,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 108,
          y = 32,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 116,
          y = 56,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 92,
          y = 104,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 68,
          y = 104,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 92,
          y = 56,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 68,
          y = 76,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 204,
          y = 48,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 208,
          y = 28,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 200,
          y = 26,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 208,
          y = 52,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 240,
          y = 48,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 124,
          y = 56,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 96,
          y = 36,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "d",
          type = "",
          shape = "ellipse",
          x = 160,
          y = 34,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 44,
          y = 84,
          width = 12,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "ellipse",
          x = 120,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "ellipse",
          x = 120,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 104,
          name = "a8",
          type = "",
          shape = "rectangle",
          x = 121,
          y = 126,
          width = 1,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "fbxs",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 105,
          name = "fbx01",
          type = "",
          shape = "rectangle",
          x = 124,
          y = 124,
          width = 3,
          height = 3,
          rotation = 180,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "fbx02",
          type = "",
          shape = "rectangle",
          x = 123,
          y = 241,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
