return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "2020.06.25",
  orientation = "orthogonal",
  renderorder = "left-down",
  width = 64,
  height = 64,
  tilewidth = 8,
  tileheight = 8,
  nextlayerid = 4,
  nextobjectid = 21,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "world",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "base",
          type = "",
          shape = "rectangle",
          x = 194,
          y = 174,
          width = 32,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "base",
          type = "",
          shape = "rectangle",
          x = 226,
          y = 198,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "base",
          type = "",
          shape = "rectangle",
          x = 202,
          y = 190,
          width = 8,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "base",
          type = "",
          shape = "rectangle",
          x = 194,
          y = 164,
          width = 8,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "base",
          type = "",
          shape = "rectangle",
          x = 202,
          y = 158,
          width = 40,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "base",
          type = "",
          shape = "rectangle",
          x = 242,
          y = 160,
          width = 8,
          height = 46,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "base",
          type = "",
          shape = "rectangle",
          x = 202,
          y = 206,
          width = 24,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "objects",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      tintcolor = { 85, 255, 255 },
      properties = {},
      objects = {
        {
          id = 2,
          name = "player1",
          type = "",
          shape = "ellipse",
          x = 202,
          y = 182,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "tree",
          type = "",
          shape = "rectangle",
          x = 196,
          y = 170,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "tree",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 160,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "tree",
          type = "",
          shape = "rectangle",
          x = 222,
          y = 162,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "tree",
          type = "",
          shape = "rectangle",
          x = 232,
          y = 160,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "tree",
          type = "",
          shape = "rectangle",
          x = 246,
          y = 164,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "tree",
          type = "",
          shape = "rectangle",
          x = 244,
          y = 174,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
